version: "3"

services:
  airflow-local-workspace:
    build: .
    ports:
      - 8081:8080
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 30
      AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 10
    volumes:
      - ./dags:/opt/airflow/dags